# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: circleci/node:19.6.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Test
          command: npm run test
  build:
    docker:
      - image: circleci/node:19.6.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build Project
          command: npm run build
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Configure Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
              gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy
          command: |
            gcloud app deploy app.yaml
            gcloud app browse

workflows:
  build-and-deploy:
    jobs:
      - test:
          name: test
          filters:
            branches:
              only: main
      - build:
          name: build
          requires:
            - test
      - deploy:
          name: deploy
          requires:
            - build