version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
  node: circleci/node@5.1.0

jobs:
  build_test:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run tests
          command: npm test
  deploy_staging:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Configure gcloud
          command: |
            echo $STAGE_GCLOUD_SERVICE_KEY | base64 -d | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${STAGE_PROJECT_ID}
            gcloud config set run/region ${STAGE_REGION}
            gcloud auth configure-docker
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t gcr.io/${STAGE_PROJECT_ID}/${STAGE_APP_NAME}:${CIRCLE_SHA1} .
            docker tag gcr.io/${STAGE_PROJECT_ID}/${STAGE_APP_NAME}:${CIRCLE_SHA1} gcr.io/${STAGE_PROJECT_ID}/${STAGE_APP_NAME}:latest
      - run:
          name: Push Docker image to Container Registry
          command: |
            docker push gcr.io/${STAGE_PROJECT_ID}/${STAGE_APP_NAME}:${CIRCLE_SHA1}
            docker push gcr.io/${STAGE_PROJECT_ID}/${STAGE_APP_NAME}:latest
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy ${APP_NAME} --region ${STAGE_REGION} --image gcr.io/${STAGE_PROJECT_ID}/${STAGE_APP_NAME}:${CIRCLE_SHA1} --platform managed --allow-unauthenticated --project ${STAGE_PROJECT_ID}
  deploy_production:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Configure gcloud
          command: |
            echo $PROD_GCLOUD_SERVICE_KEY | base64 -d | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${PROD_PROJECT_ID}
            gcloud config set run/region ${PROD_REGION}
            gcloud auth configure-docker
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t gcr.io/${PROD_PROJECT_ID}/${PROD_APP_NAME}:${CIRCLE_SHA1} .
            docker tag gcr.io/${PROD_PROJECT_ID}/${PROD_APP_NAME}:${CIRCLE_SHA1} gcr.io/${PROD_PROJECT_ID}/${PROD_APP_NAME}:latest
      - run:
          name: Push Docker image to Container Registry
          command: |
            docker push gcr.io/${PROD_PROJECT_ID}/${PROD_APP_NAME}:${CIRCLE_SHA1}
            docker push gcr.io/${PROD_PROJECT_ID}/${PROD_APP_NAME}:latest
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy ${PROD_APP_NAME} --region ${PROD_REGION} --image gcr.io/${PROD_PROJECT_ID}/${PROD_APP_NAME}:${CIRCLE_SHA1} --platform managed --allow-unauthenticated --project ${PROD_PROJECT_ID}
workflows:
  build_test_deploy:
    jobs:
      - build_test
      - deploy_staging:
          requires:
            - build_test
          filters:
            branches:
              only: staging
      - deploy_production:
          requires:
            - build_test
          filters:
            branches:
              only: production