name: cloudrun-app
#Test

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          docker build . --tag gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/cloudrun-app:latest
      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/cloudrun-app:latest
      - name: Deploy
        run: |-
          gcloud run deploy cloudrun-app \
          --region eu-west1 \
          --image gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/cloudrun-app:latest \
          --platform "managed" \
          --quiet